// Vendor prices imported from Validation sheet (Sep 2026) -- 703 product families.
// Values are BASE UNIT prices; Buy N / Pack of N multipliers are applied separately.
export const DEFAULT_VENDOR_PRICES = {
  "aurora crystal watch with personalised bracelet stack": 407,
  "eternal spark mangalsutra necklace with ruby pendant": 150,
  "exquisite emerald and diamond mangalsutra necklace": 150,
  "radiant garnet and diamond mangalsutra necklace": 150,
  "radiant mangalsutra necklace with star pendant": 150,
  "aureon watch with personalised bracelet stack": 267,
  "dazzling diamond studded mangalsutra necklace": 150,
  "elegant ruby and diamond mangalsutra necklace": 150,
  "valentine days earring hamper 8 earrings": 310,
  "glossy bow hair claw (transparent clear": 18,
  "period cramp comfort heating pad hamper": 309,
  "22k plated adjustable single name ring": 180,
  "blooming grace flower diamond necklace": 305,
  "mesmerizing charm mangalsutra necklace": 150,
  "12 in 1 personalised earring gift box": 591,
  "eclipse elegance mangalsutra bracelet": 105,
  "enchant�� circle of elegance necklace": 160,
  "eternal sparkle diamond stud necklace": 315,
  "name necklace with personalised photo": 150,
  "obsidian sparkle mangalsutra bracelet": 155,
  "timeless emerald mangalsutra necklace": 150,
  "butterfly heart couple name necklace": 160,
  "dual tone matt mini hair claw (peach": 8,
  "emerald sparkle mangalsutra necklace": 150,
  "enchanté circle of elegance necklace": 160,
  "signature couple heart name necklace": 160,
  "you are my favourite madness perfume": 390,
  "cute crochet fruit & flower tic tac": 18,
  "embraced heart mangalsutra necklace": 105,
  "enchant circle of elegance necklace": 160,
  "imperial jewel mangalsutra bracelet": 135,
  "infinite love interlinked heart set": 240,
  "karungali mala with govt. certified": 85,
  "pastel blossom mini hair claw clips": 8,
  "personalised wine glass for couples": 250,
  "radio designer clutch cum sling bag": 600,
  "classic grace mangalsutra necklace": 150,
  "diamond heart double name necklace": 150,
  "golden geometry earring collection": 41,
  "majestic aura mangalsutra necklace": 105,
  "pack of 2 memory t-shirt oversized": 260,
  "princess halo diamond necklace set": 260,
  "royal elegance diamond mangalsutra": 115,
  "ruby embedded mangalsutra necklace": 150,
  "classic ruby mangalsutra necklace": 150,
  "eternal bond mangalsutra necklace": 150,
  "fimo beads name necklace for kids": 180,
  "floral transparent hair claw clip": 19,
  "mangalsutra lucky clover necklace": 85,
  "minimal matte rectangle hair claw": 15,
  "parisian butterfly pearl earrings": 27,
  "12 in 1 earring folding gift box": 591,
  "celestial water drop diamond set": 310,
  "diamond studded initial necklace": 375,
  "dreamy butterfly pearl hair clip": 19,
  "dual hearts couple name necklace": 160,
  "fairy wings mangalsutra bracelet": 170,
  "personalised name earring hamper": 170,
  "12 in 1 personalised jhumka box": 250,
  "amethyst bloom pendant necklace": 92,
  "amethyst teardrop halo necklace": 101,
  "bollywood 8 in 1 earring hamper": 320,
  "charmtrail mangalsutra necklace": 150,
  "cute daisy & blossom snap clips": 16,
  "golden minimalist drop earrings": 27,
  "kids personalised bead necklace": 70,
  "knotted pearl elegance earrings": 18,
  "korean style mini fur hair claw": 12,
  "minimal beads anklets pack of 2": 30,
  "pearl noir mangalsutra necklace": 100,
  "premium gift box with gift wrap": 22,
  "bluebliss mangalsutra necklace": 159,
  "butterfly couple name necklace": 160,
  "enchant√© mangalsutra necklace": 115,
  "fruit heart mini hair claw set": 17,
  "golden seashell pearl necklace": 96,
  "gradient mini flower hair claw": 17,
  "heritage pearl square earrings": 34,
  "initial arabic ring adjustable": 180,
  "iridescent heart hair clip set": 12.5,
  "luxe cylinder pendant necklace": 180,
  "luxe noir mangalsutra necklace": 130,
  "minimal bead anklet- pack of 1": 30,
  "personalised wallet & keychain": 90,
  "pinkbliss mangalsutra necklace": 150,
  "charisma mangalsutra necklace": 150,
  "cute blossom & bow hair clips": 13,
  "cutiepie name necklace hamper": 200,
  "dual tone matt mini hair claw": 8,
  "enchanté mangalsutra necklace": 115,
  "infinity couple name necklace": 160,
  "korean style matt hair claw (": 15,
  "korean style matt hair claw )": 15,
  "mini cute shoe hair clips set": 13,
  "modern teardrop hoop earrings": 51,
  "red loop clutch cum sling bag": 600,
  "royal amethyst bloom necklace": 92,
  "royal elegant pearly necklace": 310,
  "valentine days earring hamper": 320,
  "crystal square stud earrings": 22,
  "diamond bubble initial rings": 61.8,
  "elegant fabric bow hair clip": 29,
  "elegant mangalsutra necklace": 130,
  "enchant mangalsutra necklace": 115,
  "endless love lariat necklace": 93,
  "floral printed bow hair clip": 11,
  "golden bloom & leaf earrings": 35,
  "interlinked diamond bracelet": 130,
  "ivory blossom pearl earrings": 31,
  "mini flower & bow hair clips": 24,
  "mosaic pearl square earrings": 17,
  "mystic charm clover necklace": 190,
  "noir square pendant necklace": 76,
  "pearly statement rose anklet": 35,
  "personalised kids sunglasses": 60,
  "sparkling solitaire necklace": 190,
  "teardrop mangalsutra pendant": 70,
  "you are my sunshine necklace": 150,
  "cat's eye teardrop earrings": 41,
  "classic pearl drop earrings": 15,
  "clover mangalsutra necklace": 70,
  "couple name ring adjustable": 180,
  "cute cartoon mini hair claw": 13,
  "floral mangalsutra bracelet": 155,
  "flower claw clip set (peach": 40,
  "geo sparkle square earrings": 27,
  "glossy pastel bow hair claw": 20,
  "golden heart twist earrings": 16,
  "golden hollow drop earrings": 18,
  "golden twist layer earrings": 24,
  "korean style matt hair claw": 15,
  "mermaid pearl halo earrings": 23,
  "mini matte flower claw clip": 16,
  "mini matte square hair claw": 12,
  "onyx double square earrings": 26,
  "pearl leaf pendant earrings": 34,
  "personalized name necklaces": 95,
  "purple floral halo necklace": 98,
  "reversible octopus soft toy": 125,
  "crystal butterfly bracelet": 104,
  "enchanted heartbeat anklet": 225,
  "evil eye infinity bracelet": 65,
  "flower matt mini hair claw": 8,
  "golden layered twist hoops": 32,
  "golden petite bow earrings": 15,
  "graceful swan necklace set": 280,
  "heart couple name necklace": 160,
  "heart name ring adjustable": 100,
  "interlinked heart necklace": 190,
  "majestic evil eye necklace": 130,
  "personalised bike keychain": 75,
  "personalised cuff bracelet": 72,
  "personalised name hand bag": 300,
  "spring leaf pearl earrings": 25,
  "sunflower hair rubber band": 50,
  "aura mangalsutra necklace": 105,
  "comfrt club hoodie unisex": 693,
  "eclipse elegance bracelet": 105,
  "eternal heart diamond set": 340,
  "everlasting guardian bell": 35,
  "fishtail sparkle earrings": 22,
  "golden bean drop earrings": 20,
  "lustre royale diamond set": 265,
  "mangalsurta name necklace": 95,
  "mangalsutra name necklace": 95,
  "morse code name jewellery": 47,
  "pastel blossom hair clips": 24,
  "personalised box tote bag": 850,
  "personalised car keychain": 75,
  "personalised photo puzzle": 200,
  "personalized name handbag": 300,
  "petite bow pearl earrings": 23,
  "ribbed shell stud earring": 44,
  "ruby mangalsutra bracelet": 115,
  "tulip pearl drop earrings": 20,
  "zircon lightning necklace": 100,
  "birthstone name necklace": 118,
  "bow shaped alligator pin": 16,
  "butterfly diamond anklet": 27,
  "butterfly glaze earrings": 23,
  "butterfly sheen earrings": 24,
  "crochet positive penguin": 230,
  "dainty evil eye necklace": 32,
  "diamond majesty necklace": 180,
  "earrings gift box 16 pcs": 752,
  "ethereal hollow necklace": 160,
  "everlasting prism anklet": 225,
  "floral radiance bracelet": 200,
  "frangipani hair claw set": 40,
  "hexagon initial necklace": 172,
  "if lost return to tshirt": 260,
  "infinity korean necklace": 140,
  "interlinked heart anklet": 27,
  "matt rectangle hair claw": 15,
  "mini matte hair claw set": 5,
  "morse code name necklace": 47,
  "ocean mist gemstone kada": 200,
  "pack of 2 memory t-shirt": 260,
  "pearl aeroplane earrings": 95,
  "personalised waist chain": 150,
  "petite heart pearl studs": 15,
  "solitaire spark necklace": 129,
  "statement cross earrings": 20,
  "xl matte shell hair claw": 20,
  "bow knot heart necklace": 105,
  "butterfly drop earrings": 21,
  "butterfly name necklace": 150,
  "camellia bloom earrings": 30,
  "crystal barrel necklace": 45,
  "crystal tennis bracelet": 68,
  "diamond tennis bracelet": 193,
  "eternal heart necklace-": 120,
  "glossy orchid hair claw": 23,
  "halo butterfly earrings": 34,
  "i love you bar necklace": 75,
  "infinity heart necklace": 80,
  "italian linked bracelet": 150,
  "lavender bloom earrings": 27,
  "minimal tennis bracelet": 107,
  "open heart necklace set": 88,
  "oversized bow hair claw": 66,
  "papillon pearl earrings": 25,
  "personalised name rakhi": 100,
  "resin initial neckalce-": 20,
  "reversible tag necklace": 180,
  "royal radiance necklace": 190,
  "sparkle clutch earrings": 40,
  "statement rose necklace": 218,
  "sunflower hair claw set": 40,
  "woodland charm earrings": 24,
  "celestial reverie kada": 200,
  "celestial whisper kada": 200,
  "classic band name ring": 100,
  "classic heart necklace": 85,
  "crystal crown bracelet": 200,
  "diamond cross necklace": 100,
  "diamond heart necklace": 140,
  "emerald heart necklace": 130,
  "emerald stone necklace": 218,
  "eternal heart necklace": 120,
  "eternal love heart set": 315,
  "everlasting knot rakhi": 43,
  "floral elegance anklet": 175,
  "graceful opulence kada": 200,
  "heart & stone necklace": 230,
  "heart harmony bracelet": 100,
  "honeybee stud earrings": 18,
  "linked circle necklace": 167,
  "luminous charm pendant": 160,
  "mahadev rudraksh rakhi": 150,
  "mahakal rudraksh rakhi": 150,
  "maple sparkle earrings": 24,
  "minimal heart bracelet": 40,
  "moonlit charm bracelet": 100,
  "pearl cluster earrings": 40,
  "pearl whisper necklace": 89,
  "skyward wings earrings": 120,
  "smiley golden necklace": 167,
  "snow camellia earrings": 20,
  "studded heart earrings": 95,
  "sweety hearty bracelet": 340,
  "timeless radiance kada": 200,
  "trishul rudraksh rakhi": 150,
  "twinkle grace bracelet": 100,
  "vintage charm earrings": 19,
  "aurora bloom bracelet": 100,
  "capybara squishy lamp": 400,
  "couples home keychain": 40,
  "crochet sunflower pot": 200,
  "crowned elegance kada": 200,
  "diamond lock necklace": 170,
  "double heart necklace": 30,
  "emerald glow earrings": 30,
  "eternal knot necklace": 210,
  "flower snap hair clip": 15,
  "forever love bracelet": 30,
  "gleaming gem necklace": 160,
  "golden daisy necklace": 64,
  "golden heart necklace": 18,
  "golden pleat earrings": 20,
  "golden teddy necklace": 512,
  "infinity bow necklace": 80,
  "infinity diamond ring": 90,
  "initial evil eye kada": 215,
  "link of love necklace": 160,
  "linked charm bracelet": 310,
  "lock and key necklace": 260,
  "lock pendant necklace": 115,
  "lucky clover necklace": 80,
  "matt flower hair claw": 7,
  "minimal rose necklace": 100,
  "money magnet bracelet": 85,
  "moonlit elegance kada": 200,
  "nayantara mangalsutra": 70,
  "oval diamond necklace": 160,
  "pearl shell hair clip": 16,
  "pearly heart bracelet": 35,
  "pearly heart earrings": 95,
  "pearly snake bracelet": 35,
  "plain facial headband": 27,
  "plum blossom earrings": 23,
  "princess diamond ring": 95,
  "punjabi name necklace": 115,
  "radiant prism pendant": 145,
  "secret daisy necklace": 170,
  "star pendant necklace": 167,
  "tree of life necklace": 140,
  "velvet heart bracelet": 100,
  "violet bloom earrings": 27,
  "yin and yang necklace": 27,
  "arabic name necklace": 115,
  "aurora crystal watch": 335,
  "blush tulip earrings": 30,
  "bunny charm earrings": 28,
  "cascade bar necklace": 155,
  "cat's eye leaf studs": 39,
  "chaitali mangalsutra": 70,
  "cherry red satin bow": 56.65,
  "couple name necklace": 160,
  "cupid heart bracelet": 104,
  "cute pearly bracelet": 15,
  "diy butterfly hamper": 177,
  "double name necklace": 150,
  "emerald serpent kada": 160,
  "eternal promise ring": 125,
  "floral drop earrings": 22,
  "flower claw clip set": 40,
  "flower name necklace": 115,
  "glossy bow hair claw": 18,
  "golden serenity kada": 200,
  "graceful bow pendant": 150,
  "heart stone necklace": 230,
  "leaf clover necklace": 90,
  "lustre tube necklace": 160,
  "luxe luster necklace": 180,
  "maitreyi mangalsutra": 70,
  "mini bunny hair claw": 15,
  "mini butterfly studs": 22,
  "minimal snake anklet": 14,
  "minne mouse necklace": 167,
  "morse code jewellery": 47,
  "name ring adjustable": 180,
  "noir square earrings": 23,
  "ocean bloom necklace": 83,
  "pearl mini hair claw": 8,
  "pearl teddy necklace": 218,
  "poppy pearl necklace": 100,
  "princess gift hamper": 428,
  "puffy heart necklace": 90,
  "reyanshi mangalsutra": 70,
  "rose matte hair claw": 20,
  "royal spark bracelet": 100,
  "ruby royale bracelet": 100,
  "safety name necklace": 150,
  "sapphire bloom watch": 335,
  "signature shine kada": 200,
  "smoky pearl earrings": 20,
  "soft plush scrunchie": 13,
  "starry glow necklace": 100,
  "aakriti mangalsutra": 70,
  "angel name necklace": 150,
  "anushka mangalsutra": 70,
  "anvikaa mangalsutra": 70,
  "anvitha mangalsutra": 70,
  "apeksha mangalsutra": 70,
  "aradhya mangalsutra": 70,
  "arohiya mangalsutra": 70,
  "aurora leaf pendant": 76,
  "blood bond necklace": 170,
  "butterfly name ring": 180,
  "celestial glow kada": 200,
  "champagne satin bow": 56.65,
  "chocolate satin bow": 56.65,
  "cross name necklace": 115,
  "cute panda necklace": 879,
  "daisy name keychain": 30,
  "dove heart necklace": 160,
  "dual heart bracelet": 105,
  "elegant emerald set": 225,
  "ethereal charm kada": 200,
  "evergold charm kada": 200,
  "face wash wristband": 23,
  "fairy name necklace": 150,
  "golden arc earrings": 12,
  "hindi name necklace": 115,
  "hridaya mangalsutra": 70,
  "imperial charm kada": 200,
  "indic name necklace": 95,
  "initial arabic ring": 180,
  "ishaani mangalsutra": 70,
  "ivory clover anklet": 25,
  "kairavi mangalsutra": 70,
  "korean heart anklet": 32,
  "kritika mangalsutra": 70,
  "majestic bloom kada": 200,
  "matt mini hair claw": 11,
  "minimal bead anklet": 30,
  "moonstone glow kada": 200,
  "morse code bracelet": 39,
  "name chain bracelet": 95,
  "nandita mangalsutra": 70,
  "noble radiance kada": 200,
  "parvati mangalsutra": 70,
  "pearl bow hair pins": 15,
  "pearl cube earrings": 30,
  "pearl whisper studs": 18,
  "photo eyes necklace": 130,
  "pranavi mangalsutra": 70,
  "queen name necklace": 115,
  "rose pearl earrings": 23,
  "ruchira mangalsutra": 70,
  "savitri mangalsutra": 70,
  "shiv rudraksh rakhi": 150,
  "silk petal earrings": 30,
  "srishti mangalsutra": 70,
  "sweetheart necklace": 197,
  "tropicana butterfly": 70,
  "vaidehi mangalsutra": 70,
  "varnika mangalsutra": 70,
  "velvet majesty kada": 200,
  "yashika mangalsutra": 70,
  "aadhya mangalsutra": 70,
  "aarohi mangalsutra": 70,
  "aashna mangalsutra": 70,
  "amisha mangalsutra": 70,
  "anisha mangalsutra": 70,
  "anvika mangalsutra": 70,
  "aqua elegance kada": 200,
  "aurelisse bracelet": 100,
  "avisha mangalsutra": 70,
  "bow heart earrings": 110,
  "bow mesh hair pins": 28,
  "bowfinity bracelet": 104,
  "box chain bracelet": 45,
  "butterfly bracelet": 31,
  "butterfly necklace": 197,
  "charvi mangalsutra": 70,
  "clover mangalsutra": 70,
  "comfrt club hoodie": 693,
  "crown diamond ring": 100,
  "devika mangalsutra": 70,
  "dhriti mangalsutra": 70,
  "diamond heart ring": 150,
  "dreamleaf necklace": 879,
  "eternal grace kada": 200,
  "eternal spark kada": 200,
  "foldable hair band": 18,
  "heart fur hairband": 48,
  "ishita mangalsutra": 70,
  "kanika mangalsutra": 70,
  "karungali bracelet": 98,
  "krisha mangalsutra": 70,
  "mihira mangalsutra": 70,
  "moksha mangalsutra": 70,
  "niyati mangalsutra": 70,
  "pearl bow earrings": 28,
  "prestige aura kada": 200,
  "pristine glow kada": 200,
  "radiant charm kada": 200,
  "regal serpent kada": 160,
  "regal whisper kada": 200,
  "reversible octopus": 125,
  "roshni mangalsutra": 70,
  "round snake anklet": 20,
  "royal essence kada": 200,
  "royal reverie kada": 200,
  "sapphire glow kada": 200,
  "siddhi mangalsutra": 70,
  "starlight bracelet": 104,
  "swan love bracelet": 104,
  "tendulkar bracelet": 150,
  "trisha mangalsutra": 70,
  "tulip bow earrings": 20,
  "tvisha mangalsutra": 70,
  "vaanya mangalsutra": 70,
  "vihana mangalsutra": 70,
  "yashvi mangalsutra": 70,
  "yuvika mangalsutra": 70,
  "zivara mangalsutra": 70,
  "aashi mangalsutra": 70,
  "add gift wrapping": 2,
  "affection earring": 250,
  "amara mangalsutra": 70,
  "anaya mangalsutra": 70,
  "aurora shine kada": 200,
  "avira mangalsutra": 70,
  "crystal aura kada": 200,
  "diamond heart set": 205,
  "earrings gift box": 642,
  "elina mangalsutra": 70,
  "evelisse bracelet": 100,
  "evil eye bracelet": 33,
  "evil eye designer": 600,
  "evil eye necklace": 95,
  "gauri mangalsutra": 70,
  "halo diamond ring": 150,
  "if lost return to": 260,
  "infinity bracelet": 65,
  "interlocked heart": 43,
  "kavya mangalsutra": 70,
  "keyboard keychain": 155,
  "lock & key anklet": 120,
  "luxe whisper kada": 200,
  "manvi mangalsutra": 70,
  "marielle bracelet": 100,
  "morse code anklet": 47,
  "navya mangalsutra": 70,
  "om rudraksh rakhi": 150,
  "oorja mangalsutra": 70,
  "opulent muse kada": 200,
  "orabella bracelet": 100,
  "paper clip anklet": 9,
  "paw name necklace": 115,
  "period hug hamper": 309,
  "red cherry anklet": 52.5,
  "roseline bracelet": 100,
  "royal lumina kada": 200,
  "serenade necklace": 200,
  "sneha mangalsutra": 70,
  "swara mangalsutra": 70,
  "tanvi mangalsutra": 70,
  "timeless love set": 365,
  "vanya mangalsutra": 70,
  "velvet grace kada": 200,
  "velvet spark kada": 200,
  "ziana mangalsutra": 70,
  "zyvia mangalsutra": 70,
  "asteria bracelet": 100,
  "aveline bracelet": 100,
  "avni mangalsutra": 70,
  "blueberry anklet": 35,
  "butterfly anklet": 31,
  "celeste bracelet": 100,
  "celiora bracelet": 100,
  "citrus butterfly": 70,
  "couple name ring": 180,
  "crochet bow clip": 200,
  "crown jewel kada": 395,
  "crystal bracelet": 295,
  "diamond necklace": 140,
  "divine glow kada": 200,
  "diya mangalsutra": 70,
  "dorelia bracelet": 100,
  "elegant bracelet": 105,
  "embroidery potli": 600,
  "emerald bracelet": 190,
  "emerald necklace": 105,
  "estelle bracelet": 100,
  "estoria bracelet": 100,
  "evelina bracelet": 100,
  "evelora bracelet": 100,
  "flower hair claw": 10,
  "golden aura kada": 200,
  "heart pop anklet": 30,
  "initial necklace": 20,
  "joviana bracelet": 100,
  "kashmiri bangles": 230,
  "leafora bracelet": 104,
  "myra mangalsutra": 70,
  "noble spark kada": 200,
  "orielle bracelet": 100,
  "premium gift box": 20,
  "roselle bracelet": 100,
  "ruby enamel wave": 51,
  "scissor earrings": 95,
  "sunkissed anklet": 60,
  "swan korean ring": 110,
  "tara mangalsutra": 70,
  "the pastel potli": 600,
  "tropical classic": 70,
  "veda mangalsutra": 70,
  "5 in 1 gift box": 600,
  "add premium box": 11.55,
  "amber butterfly": 70,
  "amoria bracelet": 100,
  "aviana bracelet": 100,
  "barbie hairband": 102,
  "breathing teddy": 410,
  "camera necklace": 144,
  "cherry earrings": 250,
  "clover earrings": 95,
  "eliana bracelet": 100,
  "elysia bracelet": 100,
  "evil eye anklet": 45,
  "evil eye bangle": 240,
  "fairy wings set": 205,
  "fan flair studs": 18,
  "heart name ring": 180,
  "ivoria bracelet": 200,
  "jar of emotions": 30,
  "lock key anklet": 120,
  "lumina bracelet": 100,
  "maevia bracelet": 100,
  "matte hair claw": 14,
  "nivara bracelet": 100,
  "opearl necklace": 182,
  "pearl hair claw": 18,
  "regal aura kada": 200,
  "renata bracelet": 100,
  "saturn necklace": 32,
  "selene bracelet": 100,
  "smiley necklace": 167,
  "spinflower ring": 106,
  "tavira bracelet": 100,
  "twinkling watch": 112,
  "valora bracelet": 100,
  "winora bracelet": 100,
  "zafira bracelet": 100,
  "11:11 necklace": 80,
  "cherry classic": 70,
  "circle of love": 335,
  "citrus classic": 70,
  "classic ribbed": 40,
  "crystal barrel": 72,
  "daisy bracelet": 35,
  "dazzling cross": 24,
  "elora bracelet": 100,
  "evora bracelet": 100,
  "fiora bracelet": 100,
  "forge bracelet": 150,
  "hamsa necklace": 150,
  "heart bracelet": 190,
  "heart necklace": 90,
  "heart tote bag": 428,
  "karungali mala": 85,
  "leafy bracelet": 33,
  "orbit necklace": 879,
  "retro keychain": 95,
  "rudraksh rakhi": 150,
  "teddy earrings": 95,
  "the lace potli": 600,
  "tulip bracelet": 200,
  "twisted square": 40,
  "zaria bracelet": 100,
  "amber classic": 70,
  "bow hair pins": 15,
  "clover anklet": 25,
  "crub bracelet": 150,
  "cuff bracelet": 72,
  "eternity kada": 140,
  "halo necklace": 175,
  "heart earings": 250,
  "infinity ring": 125,
  "knot bracelet": 43,
  "moon necklace": 167,
  "name bracelet": 220,
  "name necklace": 115,
  "ocean classic": 70,
  "paw name ring": 180,
  "pyrite anklet": 95,
  "rose bracelet": 155,
  "rose necklace": 90,
  "seashell glow": 70,
  "snake anklet-": 35,
  "swan earrings": 95,
  "aqua organic": 51,
  "bar necklace": 120,
  "be mine ring": 105,
  "daisy anklet": 35,
  "dog name tag": 210,
  "hamsa anklet": 95,
  "heart anklet": 23,
  "hug necklace": 120,
  "jelly anklet": 16,
  "molten heart": 44,
  "propose ring": 90,
  "snake anklet": 35,
  "aqua ribbed": 51,
  "interlocked": 44,
  "labubu doll": 750,
  "pearl bloom": 64,
  "premium box": 20,
  "heeramandi": 1500,
  "iconic bow": 70,
  "name broch": 150,
  "pearl halo": 82,
  "pearl tide": 62,
  "pool phool": 1800,
  "sculptural": 44,
  "celestial": 150,
  "heartbeat": 86,
  "name ring": 180,
  "zibu coin": 55,
  "hammered": 44,
  "hug ring": 75,
  "midnight": 70,
  "red loop": 600,
  "sapphire": 92,
  "sculpted": 40,
  "textured": 44,
  "the cone": 600,
  "classic": 40,
  "gulzaar": 400,
  "triveni": 350,
  "twisted": 44,
  "aarohi": 1600,
  "ananta": 350,
  "molten": 44,
  "sitara": 1900,
  "tarini": 1400,
  "fairy": 25,
  "leher": 1600,
  "woven": 44,
}

// Logistics costs
export const LOGISTICS_COSTS = {
  box: 34.3,            // per order (ALL orders, packed regardless)
  warrantyCard: 1.5,    // per order, COD at 70%
  freeRing: 17.51,      // per PREPAID order only
  packingBag: 3.5,      // per order, COD at 70%
  shippingPrepaid: 60,  // per prepaid order
  shippingCOD: 100,     // per COD/C2P order, at 70%
}

// COD dispatch rate (70% of COD/C2P orders actually ship)
export const COD_DISPATCH_RATE = 0.7

// Payment rates
export const C2P_AMOUNT = 150         // upfront collection for PPCOD
export const COD_DELIVERY_RATE = 0.3  // 30% of COD orders actually deliver (70% ship, ~43% of shipped deliver)

// Fee rates (on Cashfree collection only)
export const FEE_RATES = {
  cashfree: 0.0134,
  engage: 0.00134,
  checkout: 0.0077,
}

// Find vendor price from product title
// Longest-key-first so specific families win over generic substrings
// (e.g. "arabic name necklace" beats "name necklace").
const DEFAULT_KEYS_BY_LENGTH = Object.keys(DEFAULT_VENDOR_PRICES).sort((a, b) => b.length - a.length)

export function findVendorPrice(title, customPrices = {}) {
  const lower = (title || '').toLowerCase()
  const customKeys = Object.keys(customPrices).sort((a, b) => b.length - a.length)
  for (const key of customKeys) {
    if (key && lower.includes(key)) return customPrices[key]
  }
  for (const key of DEFAULT_KEYS_BY_LENGTH) {
    if (lower.includes(key)) return DEFAULT_VENDOR_PRICES[key]
  }
  return 0
}

// Detect buy multiplier from title/variant, e.g. "Buy 4 @2499" -> 4.
// Anchored right after "buy" so it reads the bundle count, not the price.
export function detectBuyMultiplier(title, variantTitle) {
  const combined = `${title} ${variantTitle || ''}`.toLowerCase()
  const m = combined.match(/buy\s*(\d+)/)
  if (m) {
    const n = parseInt(m[1], 10)
    // Sanity bounds: real bundles are small; anything huge is a mis-parse.
    if (n >= 1 && n <= 50) return n
  }
  return 1
}

// Detect pack multiplier (e.g., "Pack of 2 Both Leg")
export function detectPackMultiplier(title, variantTitle) {
  const combined = `${title} ${variantTitle || ''}`.toLowerCase()
  // Kashmiri bangles: base price is per set of 14; set of 28 = 2 units
  const bangles = combined.match(/set of\s*(\d+)\s*bangles/)
  if (bangles) return Math.max(1, Math.round(parseInt(bangles[1], 10) / 14))
  const m = combined.match(/pack of\s*(\d+)/)
  if (m) {
    const n = parseInt(m[1], 10)
    if (n >= 1 && n <= 50) return n
  }
  if (combined.includes('both leg')) return 2
  return 1
}
